name: ✨ Feature Request
description: Suggest a new feature or enhancement for Chartifact
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which component or area of Chartifact does this relate to?
      options:
        - Document Schema
        - Runtime/Sandbox
        - VS Code Extension
        - Web Viewer/Editor
        - Text/Markdown
        - Charts (Vega/Vega-Lite)
        - Tables (Tabulator)
        - Inputs (Forms)
        - Diagrams (Mermaid)
        - Images
        - Presets
        - Data Sources/REST
        - CSS/Styling
        - Documentation
        - Examples
        - Build/Tooling
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches have you thought about?

  - type: textarea
    id: examples
    attributes:
      label: Examples or Use Cases
      description: Provide examples of how this feature would be used
      placeholder: |
        Example 1: ...
        Example 2: ...

  - type: textarea
    id: mockup
    attributes:
      label: Mockups or Design Ideas
      description: If applicable, add mockups, wireframes, or code examples
      placeholder: Drag and drop images or paste code snippets here

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Blocking my use of Chartifact
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: Links to similar features in other tools, research, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched for existing feature requests to avoid duplicates
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
        - label: This feature aligns with Chartifact's goals as a declarative, interactive document format
          required: false
